# Introduction to Numpy

In this tutorial, we will give you a quick introduction to numpy using exercises. We suggest that you take a look at [Numpy's documentation](https://numpy.org/doc/stable/user/absolute_beginners.html), however we will give you a sneak peak into some of its features.


In [20]:
import numpy as np

# Create a matrix
# We create a 3x3 matrix with only zeros
# [ 0 0 0 ]
# [ 0 0 0 ]
# [ 0 0 0 ]
matA = np.zeros((3, 3))

# Let's slice the matrix so it becomes as follows:
# [ 0 0 0 ]
# [ 0 1 1 ]
# [ 0 1 1 ]
matA[1:, 1:] = 1

print(matA)

# How do you think slicing works such that we produced the desired matrix with
# the expression matA[1:, 1:] = 1?

[[0. 0. 0.]
 [0. 1. 1.]
 [0. 1. 1.]]


## Exercise
You should create the following numpy matrix

```
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
```

We have written the first line for you. Finish the implementation.
Can you do it with three lines of code using slicing?

In [17]:
matA = np.zeros((10, 10))

# Finish the implementation here

print(matA)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Exercise
You should create the following numpy matrix:

```
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
```

We have written the first line for you. You should finish the implementation.
Can you do it with two lines of code?

In [21]:
matB = np.zeros((10, 10))

# Finish the implementation here

print(matB)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Creating Arrays From Existing Data and Array Operations
Refer to [this section in the Numpy documentation](https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-create-an-array-from-existing-data) to learn more.

What you have used in the above exercises is called Numpy arrays. The Numpy array is a powerful feature of the library, it is flexible and enables us to do multiple operations that we otherwise cannot do with Python. Let's look at some typical workflows with Numpy.

### Converting Python list to Numpy array

In a few weeks, you will learn about classes in PROG1003 - Object oriented programming. We will take a quick look at classes and specifically constructors, as this will become important to us.

The simplified explanation to what a class in C++ is, is that it is a struct like in C, but with `private` access specifier by default. Both classes and structs have something called a constructor, which is the first function that is executed on instantiating an object.

```c++
#include <print>

class MyClass {
    MyClass() {
        std::println("Instantiating the class MyClass");
    }
};

int main() {
    MyClass myClass{};

    // Output: Instantiating the class MyClass
}
```

In Python, the code would look as follows:

In [23]:
class MyClass:
    def __init__(self):
        print("Instantiating the class MyClass")

myClass = MyClass()

Instantiating the class MyClass


As you can see, Python's `__init__()` method is in many ways comparable to the C++ constructor. We can use this concept to convert a Python list to a Numpy array:

In [33]:
# We create a Python list, which represents a 3D vector with components, X, Y
# and Z
vec3 = [2, 3, 1]

print("Python list:", vec3)

# We can convert it to a Numpy array using the numpy.array constructor
vec3 = np.array(vec3)
print("Numpy array:")
vec3

Python list: [2, 3, 1]
Numpy array:


array([2, 3, 1])

### Stacking

We can stack arrays. Suppose we have the matrices a1 and a2. Observe what happens when we use `vstack` and `hstack`.

In [34]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

# Figure out how we use np.vstack() and np.hstack() using the Numpy
# documentation. What is the difference in their output?
# Link: https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-create-an-array-from-existing-data

### Exercise

In the code below, we have predefined 3 matrices with the names zeros, ones, twos and threes.

With one line of code, using vstack, hstack and these three matrices, create the (numpy) matrix
```
[[0. 0. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [3. 3. 2. 2. 2.]
 [3. 3. 2. 2. 2.]
 [3. 3. 2. 2. 2.]]
```

and store it in the variable matC

In [37]:
zeros = np.zeros((2, 2))
ones = np.ones((2, 3))
twos = 2*np.ones((3, 3))
threes = 3*np.ones((3, 2))

# Implement your code here with vstack and hstack.
# Bonus: Can you do it with one line?
matC = ...

print(matC)

Ellipsis


A typical operation is to flatten a matrix, so a NxM dimensional matrix becomes a 1d matrix. Do this with `matC`.

In [39]:
# Implement your code here.
flatten_matC = ...

print(flatten_matC)

Ellipsis


Swap the rows and columns of `matC`. Tips: transpose the matrix.

In [40]:
# Implement your code here.
flipped_matC = ...

print(flipped_matC)

Ellipsis


### Matrix Operations

We can leverage Python by performing matrix multiplications. Not only do we save time, but we can perform the computations super quickly. In fact, matrix multiplications is very common in real-time applications like video games and video conferences.

We can multiply two matrices element wise, we use the `*` operator. The product is also called the Hadamard product and is useful in for example signal processing. For matrix products we use the `@` operator (or, allternatively, `matmul`.)

### Exercise

In [ ]:
# Work with these matrices
M1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
M2 = np.array([[1,1,1], [1,0,1], [1,1,1]])

# A. Compute the Hadamard product M1⋅M2 and put the result in the variable matA.
matA = ...

# B. Compute the matrix product M1⋅M2 and put the result in the variable matB.
matB = ...

# Compute the expression 2*(M1)^3+I and put the result in the variable matC.
# Here, I is the identity matrix which you can create using the function np.eye.
# The product is the matrix product.
matC = ...